POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "id": 4,
  "firstName": "",
  "lastName": "",
  "email": ""
}

###
GET http://127.0.0.1:8080/customer
Content-Type: application/json